routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	//RBAC
	Route::resource('sub-admin', 'RBAC\SubAdminController');
	Route::resource('permission', 'RBAC\PermissionController');
	Route::resource('role', 'RBAC\RoleController');
	Route::get('subadmin/active/{id}', 'RBAC\SubAdminController@changeAdminStatus')->name('subadmin.active');
	//end RBAC

	Route::resource('setting', 'Setting\SettingController');
	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');
	
	Route::put('settings/surgeprice', 'Setting\SettingController@surgePriceUpdate')->name('settings.surgeprice');
	Route::get('get/surgeprice', 'Setting\SettingController@getSurgePrice')->name('get.surgeprice');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	//service
	Route::resource('service', 'Service\ServiceTypeController');

	//vehicle
	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	//city
	Route::resource('city', 'City\CityController');

	//referral amount
	Route::resource('referral-amount', 'Referral\ReferralController');

	//taxi dispatch
	Route::resource('taxi-dispatch', 'TaxiDispatch\TaxiDispatchController');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	Route::get('passengers/search', 'Passenger\PassengerController@passengerSearch')->name('passengers.search');
	Route::get('passenger/activation/{id}', 'Passenger\PassengerController@passengerActivationProcess')->name('passenger.activation');

	Route::get('passengers/remove', 'Passenger\PassengerController@passengerRemoveProcess')->name('passengers.remove');

	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/search', 'Driver\DriverController@driverSearch')->name('drivers.search');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('drivers/remove', 'Driver\DriverController@driverRemoveProcess')->name('drivers.remove');


	//tracking driver
	Route::get('drivers/tracking/{id}', 'Driver\DriverController@trackingDriver')->name('drivers.tracking');
	Route::get('drivers/tracking/random/{id}', 'Driver\DriverController@trackingDriverRandomly')->name('drivers.tracking.random');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('payment/{type}', 'DriveReport\DriveReportController@allRequest')->name('payment');

	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');
	//get beneficiary
	Route::post('driver/get/beneficiary', 'Transaction\TransactionController@getDriverBeneficiary')->name('driver.get.beneficiary');
	//transfer beneficiary
	Route::post('driver/create/paymentgateway-transfer-beneficiary','Transaction\TransactionController@transferPayoutToBebeficiary')->name('driver.create.paymentgateway-transfer-beneficiary');
	//get flutterwave admin balance
	Route::get('driver/get/paymentgateway-balance','Transaction\TransactionController@getAdminFlutterWaveBalance')->name('driver.get.paymentgateway-balance');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/split/transaction/{id}', 'Transaction\TransactionController@passengerSplitTransaction')->name('passenger.split.transaction');

app/Http/Controllers/Api/Driver/DocumentController.php
<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use App\Model\Document\DriverDocuments;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\DB;

use Validator;

class DocumentController extends Controller
{
    public function uploadDocument(Request $request,$document_id){
        try{
            $id=Auth::user()->id;
            $rule=['file' => 'required|mimes:jpeg,bmp,png'];
            $validator=$this->requestValidation($request->all(),$rule);
            if($validator->status=="false"){
                return response(['message'=>$validator->message,"field"=>$validator->field,"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.VALIDATION_FAILED")])],422);
            }
            $Document = DriverDocuments::where('user_id', $id)->where('document_id', $document_id)->get()->toArray();
            if(!empty($Document)){
                $DriverDocuments = DriverDocuments::where('user_id', $id)->where('document_id', $document_id)->firstOrFail();
                if(isset($request->file) && !empty($request->file)){
                    $picture = $request->file->store('public/driver/'.$id.'/documents');
                    $picture=str_replace("public", "storage", $picture);
                    $DriverDocuments->url=env("baseURL").$picture;
                    $DriverDocuments->status='ASSESSING';
                    $DriverDocuments->save();
                }
            }
            else{
                if(isset($request->file) && !empty($request->file)){
                    $picture = $request->file->store('public/driver/'.$id.'/documents');
                    $picture=str_replace("public", "storage", $picture);
                    $DriverDocuments=new DriverDocuments;
                    $DriverDocuments->url=env("baseURL").$picture;
                    $DriverDocuments->user_id=$id;
                    $DriverDocuments->document_id=$document_id;
                    $DriverDocuments->status='ASSESSING';
                    $DriverDocuments->save();
                }
            }

            return response(['message'=>trans("api.SYSTEM_MESSAGE.DOCUMENT_UPDATED"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DOCUMENT_UPDATED")])],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")])],400);
        }
        catch(ModelNotFoundException $e)
        {
            return response(['message'=>'Your not authorized to access',"errors"=>array("exception"=>["Invalid credentials"])],401);
        }

    }
    public function list(Request $request)
    {
        try{
            $id=Auth::user()->id;
            $VehicleDocuments = DB::table('documents')
            ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' .$id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url'),
                        DB::raw('COALESCE((select driver_documents.expires_at  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_expires_at')
                    )
            ->where('type', 'VEHICLE')->where('status', 1)
            ->get();
            $DriverDocuments =  DB::table('documents')
            ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url'),
                        DB::raw('COALESCE((select driver_documents.expires_at  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' .$id . '),"") AS driver_document_expires_at')
                    )
                    ->where('type', 'DRIVER')->where('status', 1)
                    ->get();

                    $VehicleImage = DB::table('documents')
                    ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url   from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url')
                    )
                    ->where('type', 'VEHICLE IMAGE')->where('status', 1)
                    ->get();
                    //       $driver = Auth::user();
                    $Documnets=[
                        'VehicleDocuments' => $VehicleDocuments,
                        'DriverDocuments' => $DriverDocuments,
                        'VehicleImage' => $VehicleImage,
                        // 'id' => Auth::user()->id
                    ];

            return response(['message'=>trans("api.SYSTEM_MESSAGE.DOCUMENT_LIST"),"data"=>(array)$Documnets,"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.WORKING_AS_EXPECTED")])],200);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")])],400);
        }
        catch(ModelNotFoundException $e)
        {
            return response(['message'=>trans("api.notAuthorize"),"errors"=>array("exception"=>["Invalid credentials"])],401);
        }
    }


}

resources/views/admin/document/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Document ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.document.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <h5 style="margin-bottom: 2em;">Add Document</h5>

            <form class="form-horizontal" action="{{route('admin.document.store')}}" method="POST" enctype="multipart/form-data" role="form">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="name" class="col-xs-2 col-form-label">Document Name</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ old('name') }}" name="name" required id="name" placeholder="Document Name">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="type" class="col-xs-2 col-form-label">Document Type</label>
                    <div class="col-xs-10">
                        <select name="type" class="form-control">
                            <option value="DRIVER">Driver Review</option>
                            <option value="VEHICLE">Vehicle Review</option>
                            <option value="VEHICLE IMAGE">Vehicle Image Review</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="zipcode" class="col-xs-2 col-form-label"></label>
                    <div class="col-xs-10">
                        <button type="submit" class="btn btn-primary">Add Document</button>
                        <a href="{{route('admin.document.index')}}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/document/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Document ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.document.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Update Document</h5>

            <form class="form-horizontal" action="{{route('admin.document.update', $document->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">Document Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $document->name }}" name="name" required id="name" placeholder="Document Name">
					</div>
				</div>

                <div class="form-group row">
                    <label for="type" class="col-xs-2 col-form-label">Document Type</label>
                    <div class="col-xs-10">
                        <select name="type" class="form-control">
                            <option value="DRIVER" @if($document->type == 'DRIVER') selected @endif>Driver Review</option>
                            <option value="VEHICLE" @if($document->type == 'VEHICLE') selected @endif>Vehicle Review</option>
                            <option value="VEHICLE IMAGE" @if($document->type == 'VEHICLE IMAGE') selected @endif>Vehicle Image Review</option>
                        </select>
                    </div>
                </div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update Document</button>
						<a href="{{route('admin.document.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection

resources/views/admin/document/index.blade.php
@extends('admin.layout.base')

@section('title', 'Documents ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                <h5 class="mb-1">Documents</h5>
                @can('document_create')
                <a href="{{ route('admin.document.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Document</a>
                @endcan
                <table class="table table-striped table-bordered dataTable" id="table-2">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Document Name</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($documents as $index => $document)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$document->name}}</td>
                            <td>{{$document->type}}</td>
                            <td style="line-height: 34px;">
                            @can('document_active')
                            @if ($document->status == 1)
                                <a class="documentStatus btn btn-success btn-xs" data-id="{{$document->id}}" data-value="Inactivate" href="javascript:viod(0)"
                                     data-toggle="tooltip" title="Click to Inactive">Active</a>
                                @else
                                <a class="documentStatus btn btn-danger btn-xs" data-id="{{$document->id}}" data-value="Activate" href="javascript:viod(0)"
                                     data-toggle="tooltip" title="Click to Active">Inactive</a>
                            @endif
                            @endcan
                            @can('document_edit')
                            <a href="{{ route('admin.document.edit', $document->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                            @endcan
                            <form class="doc-delete" action="{{ route('admin.document.destroy', $document->id) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                @can('document_delete')
                                <button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                @endcan
                            </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>S.No</th>
                            <th>Document Name</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $(document).on('click','.documentStatus', function(e){
            e.preventDefault();
            var id = $(this).data("id");
            var value = $(this).data("value");
            bootbox.confirm('Are you sure to '+value+' document?',function(result){
                if (result) {
                $.ajax({
                    url: "document/active/"+id,
                    type: 'GET',
                    data: {
                            "id": id
                        },
                    success: function (response){
                        location.reload();
                    },
                    error: function (response){
                        $('.msg_err').hide();
                        $('.msg_suc').hide();
                        $('.inactive_doc').show();
                        $('.inactive_msg').html(response.responseJSON.message);
                    }
                });
              }
            });
        });

        $(document).on('click','.doc-delete',function (e) {
            e.preventDefault();
            var form=$(this);
            bootbox.confirm('Do you really want to delete?', function (res) {
            if (res){
               form.submit();
            }
            });
        });
    });
</script>

@endsection