routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	//RBAC
	Route::resource('sub-admin', 'RBAC\SubAdminController');
	Route::resource('permission', 'RBAC\PermissionController');
	Route::resource('role', 'RBAC\RoleController');
	Route::get('subadmin/active/{id}', 'RBAC\SubAdminController@changeAdminStatus')->name('subadmin.active');
	//end RBAC

	Route::resource('setting', 'Setting\SettingController');
	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');
	
	Route::put('settings/surgeprice', 'Setting\SettingController@surgePriceUpdate')->name('settings.surgeprice');
	Route::get('get/surgeprice', 'Setting\SettingController@getSurgePrice')->name('get.surgeprice');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	//service
	Route::resource('service', 'Service\ServiceTypeController');

	//vehicle
	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	//city
	Route::resource('city', 'City\CityController');

	//referral amount
	Route::resource('referral-amount', 'Referral\ReferralController');

	//taxi dispatch
	Route::resource('taxi-dispatch', 'TaxiDispatch\TaxiDispatchController');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	Route::get('passengers/search', 'Passenger\PassengerController@passengerSearch')->name('passengers.search');
	Route::get('passenger/activation/{id}', 'Passenger\PassengerController@passengerActivationProcess')->name('passenger.activation');

	Route::get('passengers/remove', 'Passenger\PassengerController@passengerRemoveProcess')->name('passengers.remove');

	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/search', 'Driver\DriverController@driverSearch')->name('drivers.search');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('drivers/remove', 'Driver\DriverController@driverRemoveProcess')->name('drivers.remove');


	//tracking driver
	Route::get('drivers/tracking/{id}', 'Driver\DriverController@trackingDriver')->name('drivers.tracking');
	Route::get('drivers/tracking/random/{id}', 'Driver\DriverController@trackingDriverRandomly')->name('drivers.tracking.random');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('payment/{type}', 'DriveReport\DriveReportController@allRequest')->name('payment');

	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');
	//get beneficiary
	Route::post('driver/get/beneficiary', 'Transaction\TransactionController@getDriverBeneficiary')->name('driver.get.beneficiary');
	//transfer beneficiary
	Route::post('driver/create/paymentgateway-transfer-beneficiary','Transaction\TransactionController@transferPayoutToBebeficiary')->name('driver.create.paymentgateway-transfer-beneficiary');
	//get flutterwave admin balance
	Route::get('driver/get/paymentgateway-balance','Transaction\TransactionController@getAdminFlutterWaveBalance')->name('driver.get.paymentgateway-balance');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/split/transaction/{id}', 'Transaction\TransactionController@passengerSplitTransaction')->name('passenger.split.transaction');

resources/views/admin/include/footer.blade.php
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-xs-center">
			<div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
				<p>
                {{ App\Http\Controllers\Controller::setting()[4]->value }}
                </p>
			</div>
		</div>
	</div>
</footer>

resources/views/admin/include/header.blade.php
<!-- Header -->
<div class="site-header">
	<nav class="navbar navbar-light">
		<div class="navbar-left">
			<a class="navbar-brand" href="{{url('admin/dashboard')}}">
			<img class="image mylogo" src="{{URL::asset(App\Http\Controllers\Controller::setting()[1]->value)}}" style="height: 100%;width: auto;">
			</a>
			<div class="toggle-button light sidebar-toggle-first float-xs-left hidden-md-up">
				<span class="hamburger"></span>
			</div>
			<div class="toggle-button-second dark float-xs-right hidden-md-up">
				<i class="ti-arrow-left1"></i>
			</div>
			<div class="toggle-button dark float-xs-right hidden-md-up" data-toggle="collapse" data-target="#collapse-1">
				<span class="more1"></span>
			</div>
		</div>
		<div class="navbar-right togglebutton navbar-toggleable-sm collapse" id="collapse-1">
			<div class="toggle-button light sidebar-toggle-second float-xs-left hidden-sm-down">
				<span class="hamburger"></span>
			</div>

			<ul class="nav navbar-nav">
				<li class="nav-item hidden-sm-down">
					<a class="nav-link toggle-fullscreen" href="javascript:void(0)">
						<i class="ti-fullscreen"></i>
					</a>
				</li>
			</ul>
			<ul class="nav navbar-nav float-md-right">
				<li class="nav-item dropdown hidden-sm-down">
					<a href="#" data-toggle="dropdown" aria-expanded="false">
						{{Auth::user()->admin_profile->first_name}}
						<span class="avatar box-48">

						@if(isset(Auth::user()->admin_profile->picture))
	                    	@if(File::exists(storage_path('app/public' .str_replace("storage", "", Auth::user()->admin_profile->picture))))
                                <img src="{{URL::asset(Auth::user()->admin_profile->picture)}}" style="height: 100%;">
                            @else
                                <img src="{{URL::asset('main/avatar.jpg')}}">
                            @endif
	                   	@else
                     		<img src="{{URL::asset('main/avatar.jpg')}}">
	                    @endif
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right animated fadeInUp">
						@can('admin_profile_access')
						<a class="dropdown-item" href="{{route('admin.profile')}}">
							<i class="ti-user mr-0-5"></i> Profile
						</a>
						@endcan
						@can('admin_change_password')
						<a class="dropdown-item" href="{{route('admin.password')}}">
							<i class="ti-settings mr-0-5"></i> Change Password
						</a>
						@endcan
						<div class="dropdown-divider"></div>

						<a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout_form').submit();">
							<i class="ti-power-off mr-0-5"></i> Sign out</a>
						<form id="logout_form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    	{{ csrf_field() }}
                		</form>

					</div>
				</li>
			</ul>

		</div>
	</nav>
</div>

resources/views/admin/include/nav.blade.php
<style>
.with-sub a ~ ul li a{
	position:relative !important;
}
.with-sub a ~ ul li a:after {
    content: "";
    width: 10px;
    height: 10px;
    background: #989898;
    z-index: 999;
    position: absolute;
    border-radius: 50%;
    left: 30px;
    top: 12px;
}
.site-sidebar .sidebar-menu > li.with-sub > a .s-caret{
	transform: rotate(0deg);
}
.site-sidebar .sidebar-menu > li.with-sub.active > a .s-caret{
	transform: rotate(180deg);
}
</style>
<div class="site-sidebar">
	<div class="custom-scroll custom-scroll-light">
		<ul class="sidebar-menu">
			@can('dashboard_access')
				<li class="menu-title">Admin Dashboard</li>
				<li>
					<a href="{{ route('admin.dashboard.index') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fas fa-tachometer-alt"></i></span>
						<span class="s-text">Dashboard</span>
					</a>
				</li>
			@endcan
				
			@can('rbac_management')
				<li class="menu-title">RBAC Management</li>

				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						{{-- <span class="s-icon"><i class="ti-crown"></i></span> --}}
						<span class="s-icon"><i class="fas fa-user-alt"></i></span>
						
						<span class="s-text">Admin</span>
					</a>
					<ul>
						<li><a href="{{ route('admin.sub-admin.index') }}">Admin Users</a></li>
						<li><a href="{{ route('admin.sub-admin.create') }}">Add New Admin Group</a></li>
					</ul>
				</li>
				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="fab fa-critical-role"></i></span>
						<span class="s-text">Roles</span>
					</a>
					<ul>
						<li><a href="{{ route('admin.role.index') }}">List Roles</a></li>
						<li><a href="{{ route('admin.role.create') }}">Add New Roles</a></li>
					</ul>
				</li>
				
			@endcan

				<li class="menu-title">Members</li>
			@can('passenger_access')
				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="fas fa-user-alt"></i></span>
						<span class="s-text">Rider</span>
					</a>
					<ul>
					@can('passenger_list')
						<li><a href="{{ route('admin.passenger.index') }}">List Riders</a></li>
					@endcan
					@can('passenger_create')
						<li><a href="{{ route('admin.passenger.create') }}">Add New Rider</a></li>
					@endcan	
					</ul>
				</li>
			@endcan

			@can('driver_access')
				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="fas fa-user-alt"></i></span>
						<span class="s-text">Driver</span>
					</a>
					<ul>
					@can('driver_list')
						<li><a href="{{ route('admin.driver.index') }}">List Drivers</a></li>
					@endcan
					@can('driver_create')
						<li><a href="{{ route('admin.driver.create') }}">Add New Driver</a></li>
					@endcan
					</ul>
				</li>
			@endcan
				
			<li class="menu-title">General</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-bar-chart" aria-hidden="true"></i></span>
					<span class="s-text">Report</span>
				</a>
				<ul>
				@can('all_request_access')
					<li><a href="{{ route('admin.payment','all') }}">Payment</a></li>
				@endcan	
				@can('no_service_found_access')
					<li><a href="{{ route('admin.request.nofound') }}">No Service Found</a></li>
				@endcan	
				@can('rejected_request_access')
					<li><a href="{{ route('admin.request.rejected') }}">Rejected Request</a></li>
				@endcan
				@can('ride_later_bookings_access')
					<li><a href="{{ route('admin.request.schedule') }}">Ride Later Bookings</a></li>
				@endcan
				@can('cancel_by_passenger_access')
					<li><a href="{{ route('admin.passenger.cancel.report') }}">Cancel By Rider</a></li>
				@endcan
				@can('cancel_by_driver_access')
					<li><a href="{{ route('admin.driver.cancel.report') }}">Cancel By Driver</a></li>
				@endcan
					<li><a href="{{ route('admin.earning.report') }}">Admin Earning</a></li>
				</ul>
			</li>

			@can('vehicle_access')
				<li class="with-sub">
					<a href="#" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="ti-car"></i></span>
						<span class="s-text">Vehicle</span>
					</a>
					<ul>
					@can('vehicle_list')
						<li><a href="{{ route('admin.vehicle.index') }}">List Vehicles</a></li>
					@endcan
					@can('vehicle_create')
						<li><a href="{{ route('admin.vehicle.create') }}">Add New Vehicle</a></li>
					@endcan
					</ul>
				</li>
			@endcan
			@can('city_access')
				<li class="with-sub">
					<a href="#" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="fas fa-city"></i></span>
						<span class="s-text">City</span>
					</a>
					<ul>
					@can('city_list')
						<li><a href="{{ route('admin.city.index') }}">List City</a></li>
					@endcan
					@can('city_create')
						<li><a href="{{ route('admin.city.create') }}">Add New City</a></li>
					@endcan
					</ul>
				</li>
			@endcan	
			@can('service_type_access')
				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="ti-view-grid"></i></span>
						<span class="s-text">Service Types</span>
					</a>
					<ul>
					@can('service_type_list')
						<li><a href="{{ route('admin.service.index') }}">List Service Types</a></li>
					@endcan
					@can('service_type_create')
						<li><a href="{{ route('admin.service.create') }}">Add New Service Type</a></li>
					@endcan
					</ul>
				</li>
			@endcan
			@can('document_access')
				<li class="with-sub">
					<a href="javascript:void(0)" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="ti-layout-tab"></i></span>
						<span class="s-text">Documents</span>
					</a>
					<ul>
					@can('document_list')
						<li><a href="{{ route('admin.document.index') }}">List Documents</a></li>
					@endcan
					@can('document_create')
						<li><a href="{{ route('admin.document.create') }}">Add New Document</a></li>
					@endcan
					</ul>
				</li>
			@endcan
			
			@can('promocode_access')
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-usd" aria-hidden="true"></i></span>
					<span class="s-text">Promocodes</span>
				</a>
				<ul>
				@can('promocode_list')
					<li><a href="{{ route('admin.promocode.index') }}">List Promocodes</a></li>
				@endcan
				@can('promocode_create')
					<li><a href="{{ route('admin.promocode.create') }}">Add New Promocode</a></li>
				@endcan
				</ul>
			</li>
			@endcan
			@can('referral_amount_access')
				<li class="with-sub">
					<a href="#" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="fa fa-usd" aria-hidden="true"></i></span>
						<span class="s-text">Referral Amount</span>
					</a>
					<ul>
					@can('referral_amount_list')
						<li><a href="{{ route('admin.referral-amount.index') }}">List Referral Amount</a></li>
					@endcan
					</ul>
				</li>
			@endcan
			@can('taxi_dispatch_access')
				<li class="with-sub">
					<a href="#" class="waves-effect  waves-light">
						<span class="s-caret"><i class="fa fa-angle-down"></i></span>
						<span class="s-icon"><i class="ti-car"></i></span>
						<span class="s-text">Taxi Dispatch</span>
					</a>
					<ul>
					@can('taxi_dispatch_list')
						<li><a href="{{ route('admin.taxi-dispatch.index') }}">List Taxi Dispatch</a></li>
					@endcan
					@can('taxi_dispatch_create')
						<li><a href="{{ route('admin.taxi-dispatch.create') }}">Add New Taxi Dispatch</a></li>
					@endcan
					</ul>
				</li>
			@endcan
			@can('cancel_reason')
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Cancel Reasons</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.cancel-reason.index') }}">List Reasons</a></li>
					<li><a href="{{ route('admin.cancel-reason.create') }}">Add New Reason</a></li>
				</ul>
			</li>
			@endcan

			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Report an issue</span>
				</a>
				<ul>
					@can('report_subject')
					<li class="with-sub">
						<a href="javascript:void(0)" class="waves-effect  waves-light">
						
							<span class="s-text">Create Subject ?</span>
							<span class="s-caret" style="float: right;"><i class="fa fa-angle-down"></i></span>
						</a>
						<ul>
							<li><a href="{{route('admin.reportIssue.customer.subject.list')}}">Rider</a></li>
							<li><a href="{{route('admin.reportIssue.driver.subject.list')}}">Driver</a></li>
						</ul>
					</li>
					@endcan
					@can('report_issue')
					<li class="with-sub">
						<a href="javascript:void(0)" class="waves-effect  waves-light">
							
							<span class="s-text">View Report an issue</span>
							<span class="s-caret" style="float: right;"><i class="fa fa-angle-down"></i></span>
						</a>
						<ul>
							<li><a href="{{route('admin.reportIssue.customer.list')}}">By Rider</a></li>
							<li><a href="{{route('admin.reportIssue.driver.list')}}">By Driver</a></li>
						</ul>
					</li>
					@endcan
				</ul>
			</li>

			@can('review_management')
			<li>
				<a href="{{ route('admin.review.driver') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fa fa-file-text" aria-hidden="true"></i></span>
					<span class="s-text">Review Management</span>
				</a>
			</li>
			@endcan
			@can('subadmin_log')
			<li>
				<a href="{{ route('admin.subadmin.log') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fa fa-file-text" aria-hidden="true"></i></span>
					<span class="s-text">Sub-admin Log</span>
				</a>
			</li>
			@endcan
			
			@can('site_setting_access')
			<li class="menu-title">Settings</li>
			<li>
				<a href="{{ route('admin.setting.index') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-settings"></i></span>
					<span class="s-text">Site Settings</span>
				</a>
			</li>
			@endcan

			@can('cms_management_access')
			<li class="menu-title">Others</li>
			<li>
				<a href="{{ route('admin.privacy.policy') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fa fa-file-text" aria-hidden="true"></i></span>
					<span class="s-text">CMS Management</span>
				</a>
			</li>
			@endcan
			@can('push_notification')
			<li>
				<a href="{{ route('admin.send.push-notification') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fa fa-bell" aria-hidden="true"></i></span>
					<span class="s-text">Push Notification</span>
				</a>
			</li>
			@endcan

			@can('passenger_chat_support')
			<li>
				<a href="{{ route('admin.passenger.chat.support') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="fa fa-bell" aria-hidden="true"></i></span>
					<span class="s-text">Passenger Chat Support</span>
				</a>
			</li>
			@endcan

			{{-- <li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="far fa-comment-dots"></i></span>
					<span class="s-text">Chat Support</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.passenger.chat.support') }}">Chat With Passenger</a></li>
					<li><a href="{{ route('admin.driver.chat.support') }}">Chat With Driver</a></li>
				</ul>
			</li> --}}

			<li class="menu-title">Account</li>
			@can('admin_profile_access')
			<li>
				<a href="{{ route('admin.profile') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="fa fa-wrench" aria-hidden="true"></i></span>
					<span class="s-text">Account Settings</span>
				</a>
			</li>
			@endcan
			@can('admin_change_password')
			<li>
				<a href="{{ route('admin.password') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="fa fa-key" aria-hidden="true"></i></span>
					<span class="s-text">Change Password</span>
				</a>
			</li>
			@endcan
			<li class="compact-hide">
				<a href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
					<span class="s-icon"><i class="ti-power-off"></i></span>
					<span class="s-text">Logout</span>
                </a>

                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
			</li>
		</ul>
	</div>
</div>