routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	//RBAC
	Route::resource('sub-admin', 'RBAC\SubAdminController');
	Route::resource('permission', 'RBAC\PermissionController');
	Route::resource('role', 'RBAC\RoleController');
	Route::get('subadmin/active/{id}', 'RBAC\SubAdminController@changeAdminStatus')->name('subadmin.active');
	//end RBAC

	Route::resource('setting', 'Setting\SettingController');
	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');
	
	Route::put('settings/surgeprice', 'Setting\SettingController@surgePriceUpdate')->name('settings.surgeprice');
	Route::get('get/surgeprice', 'Setting\SettingController@getSurgePrice')->name('get.surgeprice');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	//service
	Route::resource('service', 'Service\ServiceTypeController');

	//vehicle
	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	//city
	Route::resource('city', 'City\CityController');

	//referral amount
	Route::resource('referral-amount', 'Referral\ReferralController');

	//taxi dispatch
	Route::resource('taxi-dispatch', 'TaxiDispatch\TaxiDispatchController');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	Route::get('passengers/search', 'Passenger\PassengerController@passengerSearch')->name('passengers.search');
	Route::get('passenger/activation/{id}', 'Passenger\PassengerController@passengerActivationProcess')->name('passenger.activation');

	Route::get('passengers/remove', 'Passenger\PassengerController@passengerRemoveProcess')->name('passengers.remove');

	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/search', 'Driver\DriverController@driverSearch')->name('drivers.search');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('drivers/remove', 'Driver\DriverController@driverRemoveProcess')->name('drivers.remove');


	//tracking driver
	Route::get('drivers/tracking/{id}', 'Driver\DriverController@trackingDriver')->name('drivers.tracking');
	Route::get('drivers/tracking/random/{id}', 'Driver\DriverController@trackingDriverRandomly')->name('drivers.tracking.random');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('payment/{type}', 'DriveReport\DriveReportController@allRequest')->name('payment');

	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');
	//get beneficiary
	Route::post('driver/get/beneficiary', 'Transaction\TransactionController@getDriverBeneficiary')->name('driver.get.beneficiary');
	//transfer beneficiary
	Route::post('driver/create/paymentgateway-transfer-beneficiary','Transaction\TransactionController@transferPayoutToBebeficiary')->name('driver.create.paymentgateway-transfer-beneficiary');
	//get flutterwave admin balance
	Route::get('driver/get/paymentgateway-balance','Transaction\TransactionController@getAdminFlutterWaveBalance')->name('driver.get.paymentgateway-balance');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/split/transaction/{id}', 'Transaction\TransactionController@passengerSplitTransaction')->name('passenger.split.transaction');

resources/views/admin/setting/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Site Setting')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.setting.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <h5 style="margin-bottom: 2em;">Update Site Setting</h5>

            <form class="form-horizontal" action="{{route('admin.setting.update', $site_setting->id )}}" method="POST" enctype="multipart/form-data" role="form">

                {{csrf_field()}}
                <input type="hidden" name="_method" value="PATCH">
                <div class="form-group row">
                    <label for="key" class="col-xs-2 col-form-label">Name</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $site_setting->key }}" name="key" id="key" placeholder="Key" readonly>
                    </div>
                </div>
                @if($site_setting->key == 'site_title'||$site_setting->key == 'site_copyright'||$site_setting->key == 'web_site')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>
                @elseif($site_setting->key == 'contact_email')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="email" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>

                @elseif($site_setting->key == 'contact_number'||$site_setting->key == 'sos_number'||$site_setting->key == 'dsos_number'||$site_setting->key == 'commission'||$site_setting->key == 'passenger_cancellation_charge'||$site_setting->key == 'driver_cancellation_charge'||$site_setting->key == 'surge_price')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Value</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" value="{{ $site_setting->value }}" name="value"  id="value" placeholder="Value" required>
                    </div>
                </div>

                @elseif($site_setting->key == 'site_logo'||$site_setting->key == 'site_email_logo'||$site_setting->key == 'site_icon')
                <div class="form-group row">
                    <label for="value" class="col-xs-2 col-form-label">Logo</label>
                    <div class="col-xs-10">
                    @if(isset($site_setting->value))
                        @if(File::exists(storage_path('app/public' .str_replace("storage", "", $site_setting->value))))
                        <img style="height: 90px; margin-bottom: 15px;" src="{{URL::asset($site_setting->value)}}">
                        @else
                        <img style="height: 60px; margin-bottom: 15px;" src="{{URL::asset('asset/NO_IMG.png')}}">
                        @endif
                    @else
                        <img style="height: 60px; margin-bottom: 15px;" src="{{URL::asset('asset/NO_IMG.png')}}">
                    @endif
                        <input type="file" accept="image/*" name="value" class="dropify form-control-file" id="value" aria-describedby="fileHelp">
                    </div>
                </div>
                @endif

                <div class="form-group row">
                    <label for="zipcode" class="col-xs-2 col-form-label"></label>
                    <div class="col-xs-10">
                        <button type="submit" class="btn btn-primary">Update Site Setting</button>
                        <a href="{{route('admin.setting.index')}}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setting/index.blade.php
@extends('admin.layout.base')

@section('title', 'Site Setting')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Site Setting</h5>
            <table class="table table-striped table-bordered dataTable" id="table-setting">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($site_settings as $index => $site_setting)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>
                            @if($site_setting->key == 'site_title')
                                Title
                            @endif
                            @if($site_setting->key == 'site_logo')
                                Logo
                            @endif
                            @if($site_setting->key == 'site_email_logo')
                                Email Logo
                            @endif
                            @if($site_setting->key == 'site_icon')
                                Icon
                            @endif
                            @if($site_setting->key == 'site_copyright')
                                Copyright
                            @endif
                            @if($site_setting->key == 'surge_price')
                                Surge Price
                            @endif
                            @if($site_setting->key == 'commission')
                                Commission Charge
                            @endif
                            @if($site_setting->key == 'passenger_cancellation_charge')
                                Passenger Cancellation Charge
                            @endif
                            @if($site_setting->key == 'driver_cancellation_charge')
                                Driver Cancellation Charge
                            @endif
                            {{-- @if($site_setting->key == 'web_site')
                                Website
                            @endif --}}
                            @if($site_setting->key == 'contact_number')
                                Contact Number
                            @endif
                            @if($site_setting->key == 'contact_email')
                                Contact Email
                            @endif
                            @if($site_setting->key == 'sos_number')
                               Passenger SOS Number
                            @endif
                            @if($site_setting->key == 'dsos_number')
                               Driver SOS Number
                            @endif
                        </td>
                        <td>
                            {{-- ||$site_setting->key == 'web_site'
                            --}}

                            @if($site_setting->key == 'site_title'||$site_setting->key == 'site_copyright'||$site_setting->key == 'contact_number'||$site_setting->key == 'contact_email'||$site_setting->key == 'sos_number'||$site_setting->key == 'dsos_number'||$site_setting->key == 'passenger_cancellation_charge'||$site_setting->key == 'driver_cancellation_charge')
                                {{ $site_setting->value }}
                            @elseif($site_setting->key == 'commission')
                                {{ $site_setting->value }} %
                            @elseif($site_setting->key == 'site_logo'||$site_setting->key == 'site_email_logo'||$site_setting->key == 'site_icon')
                                @if(isset($site_setting->value))
                                    @if(File::exists(storage_path('app/public' .str_replace("storage", "", $site_setting->value))))
                                    <img src="{{URL::asset($site_setting->value)}}" style="height: 60px;">
                                    @else
                                    <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                                    @endif
                                @else
                                    <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                                @endif
                    
                            @elseif($site_setting->key == 'surge_price')
                                <span id="femaleFriend">{{ $site_setting->value }} %</span>
                            @endif
                        </td>
                        <td style="line-height: 40px;">
                            @if($site_setting->key == 'surge_price')
                                @can('site_setting_edit')
                                    <a href="{{ route('admin.setting.edit', $site_setting->id) }}" class="btn btn-info">Edit</a>
                                @endcan

                                <div class="onoffswitch">
                                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox stripe_check" id="myonoffswitch" tabindex="0" onchange="cardselect()">
                                    <label class="onoffswitch-label" for="myonoffswitch">
                                        <span class="onoffswitch-inner"></span>
                                        <span class="onoffswitch-switch"></span>
                                    </label>
                                </div>
                            @else
                                @can('site_setting_edit')
                                    <a href="{{ route('admin.setting.edit', $site_setting->id) }}" class="btn btn-info">Edit</a>
                                @endcan
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<style>
    .onoffswitch {
        position: relative; width: 90px;
        -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;
    }
    .onoffswitch-checkbox {
        position: absolute;
        opacity: 0;
        pointer-events: none;
    }
    .onoffswitch-label {
        display: block; overflow: hidden; cursor: pointer;
        border: 2px solid #999999; border-radius: 20px;
    }
    .onoffswitch-inner {
        display: block; width: 200%; margin-left: -100%;
        transition: margin 0.3s ease-in 0s;
    }
    .onoffswitch-inner:before, .onoffswitch-inner:after {
        display: block; float: left; width: 50%; height: 30px; padding: 0; line-height: 30px;
        font-size: 14px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;
        box-sizing: border-box;
    }
    .onoffswitch-inner:before {
        content: "ON";
        padding-left: 10px;
        background-color: #0da612; color: #FFFFFF;
    }
    .onoffswitch-inner:after {
        content: "OFF";
        padding-right: 10px;
        background-color: dimgrey; color: linen;
        text-align: right;
    }
    .onoffswitch-switch {
        display: block;
        width: 18px;
        background: #FFFFFF;
        position: absolute;
        top: 0;
        bottom: 0;
        border: 2px solid #999999; border-radius: 20px;
        transition: all 0.3s ease-in 0s;

        margin-bottom: 5px;
        margin-top: 3px;
        margin-right: 6px;
        margin-left: 6px;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {
        margin-left: 0;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {
        right: 0px;
    }
</style>
@endsection
@section('scripts')
<script>
function cardselect(){
    if($('.stripe_check').is(":checked")){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var status = 'YES';
        $.ajax({
            url: "{{ route('admin.settings.surgeprice') }}",
            method:"PUT",
            data:{ status: status },
            success: function(response){
                $('#femaleFriend').text(response.data.value+" %")
            },
            error: function(response){
            }
        });

    } else {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var status = 'NO';
        $.ajax({
            url: "{{ route('admin.settings.surgeprice') }}",
            method:"PUT",
            data:{ status: status },
            success: function(response){
                $('#femaleFriend').text(response.data.value+" %")
            },
            error: function(response){
            }
        });
    }
}
$(document).ready(function(){
    $('#table-setting').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: []
    });

    $.ajax({
        url: "{{ route('admin.get.surgeprice') }}",
        method:"GET",
        data:{ },
        success: function(response){
            var status = response.data.status;
            if (status=='Y') {
                $('.stripe_check').attr('checked','checked');
            }
            if (status=='N') {
                $('.stripe_check').removeAttr('checked');
            }
        },
        error: function(response){
        }
    });
});
</script>
@endsection

resources/views/admin/setting/policy.blade.php
@extends('admin.layout.base')

@section('title', 'Privacy Policy ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Rider's Privacy Policy</h5>

            @foreach($policies as $policy)
            @if($policy->key == 'page_privacy')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor">{{$policy->value}}</textarea>
                        </div>
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            @can('passenger_privacy_policy_update')
                            <button type="submit" class="btn btn-primary">Update</button>
                            @endcan
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Driver's Privacy Policy</h5>
            @foreach($policies as $policy)
            @if($policy->key == 'page_privacy_driver')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor2">{{$policy->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            @can('driver_privacy_policy_update')
                            <button type="submit" class="btn btn-primary">Update</button>
                            @endcan
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach
        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Rider's Terms and Conditions</h5>

            @foreach($policies as $policy)
            @if($policy->key == 'condition_privacy')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor1">{{$policy->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            @can('passenger_term_condition_update')
                            <button type="submit" class="btn btn-primary">Update</button>
                            @endcan
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5>Driver's Terms and Conditions</h5>

            @foreach($policies as $policy)
            @if($policy->key == 'condition_privacy_driver')
            <div className="row">
                <form action="{{ route('admin.privacy-policy.update',$policy->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="row">
                        <div class="col-xs-12">
                            <textarea name="value" id="myeditor3">{{$policy->value}}</textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-xs-10">
                            @can('driver_term_condition_update')
                            <button type="submit" class="btn btn-primary">Update</button>
                            @endcan
                            <a href="{{route('admin.dashboard.index')}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            @endif
            @endforeach

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
    CKEDITOR.replace('myeditor1');
    CKEDITOR.replace('myeditor2');
    CKEDITOR.replace('myeditor3');
</script>
@endsection