routes/web.php
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');
Route::get('email/verification/{param}', 'Api\Payment\PaymentController@verifyEmail')->name("email.verification");

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	//RBAC
	Route::resource('sub-admin', 'RBAC\SubAdminController');
	Route::resource('permission', 'RBAC\PermissionController');
	Route::resource('role', 'RBAC\RoleController');
	Route::get('subadmin/active/{id}', 'RBAC\SubAdminController@changeAdminStatus')->name('subadmin.active');
	//end RBAC

	Route::resource('setting', 'Setting\SettingController');
	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');
	
	Route::put('settings/surgeprice', 'Setting\SettingController@surgePriceUpdate')->name('settings.surgeprice');
	Route::get('get/surgeprice', 'Setting\SettingController@getSurgePrice')->name('get.surgeprice');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	//service
	Route::resource('service', 'Service\ServiceTypeController');

	//vehicle
	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	//city
	Route::resource('city', 'City\CityController');

	//referral amount
	Route::resource('referral-amount', 'Referral\ReferralController');

	//taxi dispatch
	Route::resource('taxi-dispatch', 'TaxiDispatch\TaxiDispatchController');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	Route::get('passengers/search', 'Passenger\PassengerController@passengerSearch')->name('passengers.search');
	Route::get('passenger/activation/{id}', 'Passenger\PassengerController@passengerActivationProcess')->name('passenger.activation');

	Route::get('passengers/remove', 'Passenger\PassengerController@passengerRemoveProcess')->name('passengers.remove');

	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/search', 'Driver\DriverController@driverSearch')->name('drivers.search');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('drivers/remove', 'Driver\DriverController@driverRemoveProcess')->name('drivers.remove');


	//tracking driver
	Route::get('drivers/tracking/{id}', 'Driver\DriverController@trackingDriver')->name('drivers.tracking');
	Route::get('drivers/tracking/random/{id}', 'Driver\DriverController@trackingDriverRandomly')->name('drivers.tracking.random');

	//review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('payment/{type}', 'DriveReport\DriveReportController@allRequest')->name('payment');

	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');
	//get beneficiary
	Route::post('driver/get/beneficiary', 'Transaction\TransactionController@getDriverBeneficiary')->name('driver.get.beneficiary');
	//transfer beneficiary
	Route::post('driver/create/paymentgateway-transfer-beneficiary','Transaction\TransactionController@transferPayoutToBebeficiary')->name('driver.create.paymentgateway-transfer-beneficiary');
	//get flutterwave admin balance
	Route::get('driver/get/paymentgateway-balance','Transaction\TransactionController@getAdminFlutterWaveBalance')->name('driver.get.paymentgateway-balance');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/split/transaction/{id}', 'Transaction\TransactionController@passengerSplitTransaction')->name('passenger.split.transaction');

	Route::get('passenger/transac/list', 'Transaction\TransactionController@passengerTransactionList')->name('passenger.transac.list');

	Route::get('earning/report', 'Transaction\TransactionController@adminEarning')->name('earning.report');

	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('promocodes/search', 'Promocode\PromocodeController@promocodeSearch')->name('promocodes.search');

	Route::get('passenger/cancel/report', 'CancelCharge\CancelChargeController@passengerCancelReport')->name('passenger.cancel.report');
	Route::get('driver/cancel/report', 'CancelCharge\CancelChargeController@driverCancelReport')->name('driver.cancel.report');
	//log report
	Route::get('subadmin/log', 'Log\SubAdminLogController@getLogReport')->name('subadmin.log');
	Route::post('subadmin/log/report','Log\SubAdminLogController@getSubadminLog')->name('subadmin.log.report');

	//send push notification
	Route::get('send/push-notification','PushNotification\PushNotificationController@index')->name('send.push-notification');

app/Http/Controllers/Api/Driver/DocumentController.php
<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use App\Model\Document\DriverDocuments;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\DB;

use Validator;

class DocumentController extends Controller
{
    public function uploadDocument(Request $request,$document_id){
        try{
            $id=Auth::user()->id;
            $rule=['file' => 'required|mimes:jpeg,bmp,png'];
            $validator=$this->requestValidation($request->all(),$rule);
            if($validator->status=="false"){
                return response(['message'=>$validator->message,"field"=>$validator->field,"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.VALIDATION_FAILED")])],422);
            }
            $Document = DriverDocuments::where('user_id', $id)->where('document_id', $document_id)->get()->toArray();
            if(!empty($Document)){
                $DriverDocuments = DriverDocuments::where('user_id', $id)->where('document_id', $document_id)->firstOrFail();
                if(isset($request->file) && !empty($request->file)){
                    $picture = $request->file->store('public/driver/'.$id.'/documents');
                    $picture=str_replace("public", "storage", $picture);
                    $DriverDocuments->url=env("baseURL").$picture;
                    $DriverDocuments->status='ASSESSING';
                    $DriverDocuments->save();
                }
            }
            else{
                if(isset($request->file) && !empty($request->file)){
                    $picture = $request->file->store('public/driver/'.$id.'/documents');
                    $picture=str_replace("public", "storage", $picture);
                    $DriverDocuments=new DriverDocuments;
                    $DriverDocuments->url=env("baseURL").$picture;
                    $DriverDocuments->user_id=$id;
                    $DriverDocuments->document_id=$document_id;
                    $DriverDocuments->status='ASSESSING';
                    $DriverDocuments->save();
                }
            }

            return response(['message'=>trans("api.SYSTEM_MESSAGE.DOCUMENT_UPDATED"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DOCUMENT_UPDATED")])],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")])],400);
        }
        catch(ModelNotFoundException $e)
        {
            return response(['message'=>'Your not authorized to access',"errors"=>array("exception"=>["Invalid credentials"])],401);
        }

    }
    public function list(Request $request)
    {
        try{
            $id=Auth::user()->id;
            $VehicleDocuments = DB::table('documents')
            ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' .$id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url'),
                        DB::raw('COALESCE((select driver_documents.expires_at  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_expires_at')
                    )
            ->where('type', 'VEHICLE')->where('status', 1)
            ->get();
            $DriverDocuments =  DB::table('documents')
            ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url'),
                        DB::raw('COALESCE((select driver_documents.expires_at  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' .$id . '),"") AS driver_document_expires_at')
                    )
                    ->where('type', 'DRIVER')->where('status', 1)
                    ->get();

                    $VehicleImage = DB::table('documents')
                    ->select('documents.*',
                        DB::raw('COALESCE((select driver_documents.status  from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_status'),
                        DB::raw('COALESCE((select driver_documents.url   from driver_documents where documents.id=driver_documents.document_id AND driver_documents.user_id=' . $id . '),"") AS driver_document_url')
                    )
                    ->where('type', 'VEHICLE IMAGE')->where('status', 1)
                    ->get();
                    //       $driver = Auth::user();
                    $Documnets=[
                        'VehicleDocuments' => $VehicleDocuments,
                        'DriverDocuments' => $DriverDocuments,
                        'VehicleImage' => $VehicleImage,
                        // 'id' => Auth::user()->id
                    ];

            return response(['message'=>trans("api.SYSTEM_MESSAGE.DOCUMENT_LIST"),"data"=>(array)$Documnets,"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.WORKING_AS_EXPECTED")])],200);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.DATABASE_EXCEPTION")],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG"),"data"=>[],"errors"=>array("exception"=>[trans("api.SYSTEM_MESSAGE.SOMETHING_WENT_WRONG")])],400);
        }
        catch(ModelNotFoundException $e)
        {
            return response(['message'=>trans("api.notAuthorize"),"errors"=>array("exception"=>["Invalid credentials"])],401);
        }
    }


}

app/Http/Controllers/Api/Driver/EmergencyContactController.php
<?php

resources/views/admin/driver/carimage.blade.php
@extends('admin.layout.base')

@section('title', 'Car Images')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Car Images</h5>
            <a href="{{ route('admin.driver.index') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-angle-left"></i> Back</a>
            <table class="table table-striped table-bordered dataTable" id="table-carimage">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($carimages as $index => $carimage)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>
                            @if(isset($carimage->image_url))
                                @if(File::exists(storage_path('app/public' .str_replace("storage", "", $carimage->image_url))))
                                    <img src="{{URL::asset($carimage->image_url)}}" style="height: 200px; width: 250px;">
                                @else
                                    <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                                @endif
                            @else
                                <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
$(document).ready(function(){
    $('#table-carimage').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: []
    } );
});
</script>
@endsection

resources/views/admin/driver/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Driver ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.driver.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Add Driver</h5>

            <form class="form-horizontal" action="{{route('admin.driver.store' )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	
				<div class="form-group row">
					<label for="first_name" class="col-xs-2 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}" id="first_name" placeholder="First Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-2 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}" id="last_name" placeholder="Last Name" required>
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-xs-2 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" name="email" value="{{ old('email') }}" id="email" placeholder="Email">
					</div>
				</div>

				<div class="form-group row">
					<label for="picture" class="col-xs-2 col-form-label">Picture</label>
					<div class="col-xs-10">
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row">
					<label for="mobile" class="col-xs-2 col-form-label">Mobile</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="mobile" id="mobile" placeholder="Mobile No" required>
						<input type="hidden" name="code" id="code">
					</div>
				</div>

				<div class="form-group row">
					<label for="dob" class="col-xs-2 col-form-label">Date of Birth</label>
					<div class="col-xs-10">
						<input class="form-control" type="date" name="dob" value="{{ old('dob') }}" id="dob">
					</div>
				</div>
				<div class="form-group row">
					<label for="gender" class="col-xs-2 col-form-label">Gender</label>
					<div class="col-xs-10">
						<input type="radio" id="Male" name="gender" value="Male">
						<label for="Male">Male</label><br>
						<input type="radio" id="Female" name="gender" value="Female">
						<label for="Female">Female</label>
					</div>
				</div>

				<div class="form-group row">
					<label for="city" class="col-xs-2 col-form-label">City</label>
					<div class="col-xs-10">
						<select name="city" id="city" class="form-control" required>
						<option value="">Select City</option>
						@foreach($cities as $city)
							<option value="{{$city->city_id}}">{{$city->name}}</option>
						@endforeach
						</select>
					</div>
				</div>

				<div class="form-group row">
					<label for="service_type_id" class="col-xs-2 col-form-label">Service Type</label>
					<div class="col-xs-10">
						<select name="service_type_id" id="service_type_id" class="form-control" required>
						<option value="">Select Service Type</option>
						@foreach($ServiceTypeMstDatas as $ServiceTypeMstData)
							<option value="{{$ServiceTypeMstData['id']}}">{{$ServiceTypeMstData['name']}}</option>
						@endforeach
						</select>
					</div>
				</div>

				<div class="form-group row">
					<label for="car_make" class="col-xs-2 col-form-label">Car Make</label>
					<div class="col-xs-10">
						<select name="car_make" id="car_make" class="form-control" required>
						
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label for="car_model" class="col-xs-2 col-form-label">Car Model</label>
					<div class="col-xs-10">
						<select name="car_model" id="car_model" class="form-control" required>
						
						</select>
						{{-- <input type="text" name="car_model" id="car_model" class="form-control" placeholder="Car Model" readonly> --}}
					</div>
				</div>
				<div class="form-group row">
					<label for="model_year" class="col-xs-2 col-form-label"> Model Year</label>
					<div class="col-xs-10">
						<select name="model_year" id="model_year" class="form-control" required>
						
						</select>
						{{-- <input type="text" name="model_year" id="model_year" class="form-control" placeholder="Model Year" readonly> --}}
					</div>
				</div>
				 
				<div class="form-group row">
					<label for="car_number" class="col-xs-2 col-form-label">Car Number</label>
					<div class="col-xs-10">
						<input type="text" name="car_number" id="car_number" class="form-control" placeholder="Car Number" value="{{ old('car_number') }}" required>
					</div>
				</div>
				
				<div class="form-group row">
					<label for="vehicle_color" class="col-xs-2 col-form-label">Vehicle Color</label>
					<div class="col-xs-10">
						<input type="text" name="vehicle_color" id="vehicle_color" class="form-control" placeholder="Vehicle Color" value="{{ old('vehicle_color') }}" required>
					</div>
				</div>

				<div class="form-group row password">
					<label for="password" class="col-xs-2 col-form-label">Password</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password" id="password" placeholder="Password" value="{{ old('password') }}" required>
					</div>
				</div>
				<div class="form-group row">
					<label for="password_confirmation" class="col-xs-2 col-form-label">Password Confirmation</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password_confirmation" value="{{ old('password_confirmation') }}" id="password_confirmation" placeholder="Re-type Password">
					</div>
				</div>


				{{-- <div class="form-group row">
					<label for="car_plate_number" class="col-xs-2 col-form-label">Car Plate Number</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" name="car_plate_number" value="{{ old('car_plate_number') }}" id="car_plate_number" placeholder="Car Plate Number" required>
					</div>
				</div> --}}
				{{-- <div class="form-group row">
					<label for="car_number_expire_date" class="col-xs-2 col-form-label">Car Number Plate Expiry Date</label>
					<div class="col-xs-10">
						<input class="form-control" type="date" name="car_number_expire_date" value="{{ old('car_number_expire_date') }}" id="car_number_expire_date" placeholder="Car Number Expire Date" required>
					</div>
				</div> --}}

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Add Driver</button>
						<a href="{{route('admin.driver.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>
<style type="text/css">.iti { width: 100%; }</style>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/css/intlTelInput.css">
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.15/js/intlTelInput-jquery.min.js"></script>
 <script>
	jq = jQuery.noConflict();

    use :
   		var s = jq("#mobile").intlTelInput({
			autoPlaceholder: 'polite',
   			separateDialCode: true,
   			formatOnDisplay: true,
   			initialCountry: 'ng',
   			preferredCountries:["ng"]
   		});

   	insteadof :
   		var d = jq("#mobile").intlTelInput("getSelectedCountryData").dialCode;
   		jq("#code").val(d);
		jq(document).on('countrychange', function (e, countryData) {
        	jq("#code").val((jq("#mobile").intlTelInput("getSelectedCountryData").dialCode));
    	});
</script>

@endsection
@section('scripts')
<script>
  	$(document).ready(function() {
	    const servicetype = '{{ old('service_type_id') }}';
	    if(servicetype !== '') {
	      $('#service_type_id').val(servicetype);
	    }

	$('#car_make').change(function(e){
		e.preventDefault()
        var make = $(this).val();
        $.ajaxSetup({
            headers:{
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        // $(".overlay").show();
        $.ajax({
            url: "{{ route('admin.get.admin.model') }}",
            method: "POST",
            data: {make: make},
            success: function(response){
                // $(".overlay").hide();
                $('#car_model').empty();
                var options = '<option value="">Choose Car Model</option>';
                $.each(response.data, function(key, value) {
                    options += '<option style="color:#080600;" value="'+value.model+'">'+value.model+'</option>';
                });
                $('#car_model').append(options);
                
                $('#model_year').html('');
            },
            error: function(response){
                // $(".overlay").hide();
                if (response.status == 422){
                    $('#car_model').html('');
                    $('#model_year').html('');
                } 
            }
        });
    });


    $('#car_model').change(function(){
        var model = $(this).val();
        var make = $('#car_make').val();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        //$(".overlay").show();
        $.ajax({
            url: "{{ route('admin.get.admin.year') }}",
            method: "POST",
            data: {make: make, model: model},
            success: function(response){
                //$(".overlay").hide();
                $('#model_year').empty();
                var options = '<option value="">Choose Model Year</option>';
                $.each(response.data, function(key, value) {
                    options += '<option style="color:#080600;" value="'+value.year+'">'+value.year+'</option>';
                });
                $('#model_year').append(options);
            },
            error: function(response){
                //$(".overlay").hide();
                if (response.status == 422){
                    $('#model_year').html('');
                }
            }
        });
    });

    $.ajax({
        url: "{{ route('admin.get.admin.make') }}",
        method: "GET",
        data: {},
        success: function(response){
            console.log(response);
            $('#car_make').empty();
            var options = '<option value="">Choose Car Make</option>';
            $.each(response.data, function(key, value) {
              options += '<option style="color:#080600;" value="'+value.make+'">'+value.make+'</option>';
            });
            $('#car_make').append(options);
        },
        error: function(response){
            console.log(response);
        }
    });

  	});
</script>
@endsection